### ISSUE TITLE
Wrong Instrument Index Selected

### ISSUE THREAD

**Issue by Lhoto** [Minimal-C/FactorioTextToSpeech#1]
Reposting issue here for notification since the mod portal doesn't notify you of new threads.

Hey again Minimal!

I found another bug, this one probably isn't an API limitation. One of the mods I'm using ([Soundpack: alerts and sirens](https://mods.factorio.com/mods/Arcitos/Soundpack-alerts-and-sirens)) adds another category of sounds for speakers, labeled alerts 2. With this mod and yours in use, it appears as though the blueprint chooses the wrong instrument.

I did some digging, and I believe the issue is how you're searching for the right instrument in getCompatibleVoiceInstrumentId(), lines 245 - 255 in textToSpeechGui.lua.

**My reasoning behind this:**
1. It picks steel drums, which is one index behind male voice in the dropdown
2. Mods load by rank (dependency related if I remember correctly), after which mods load in alphabetical order, meaning that the other mod loads before yours, taking the first custom instrument index/shifting another instrument to that index

This would imply that the getCompatibleVoiceInstrumentId() function is defaulting to the index based search rather than the string based one. It could be something else, but that's just what I've thought of/found so far.

Regardless, thanks for the great mod, as well as all the effort you've poured into it! I just recently made a mod myself (albeit a crappy one), so I now have an even greater appreciation for what you've done here.

**Comment by Minimal-C** [comment]
Hey! Dang dude, I gotta thank you again for your diligence, you're helping me out a bunch! Yeah GitHub is far more convenient for bug reporting, though I hear the new Factorio mod portal is going to improve alot of issues, no idea when it drops though.

Okay, so you're entirely correct, down to the method, I really don't test thoroughly enough for these cases (why test when you can write more code, right? lol). 

It was a silly mistake, there was a comparison of a Factorio "localized string" to a regular string (Line 249), which doesn't work (also bad practice for other reasons even if it worked), but it defaulted to the correct hard coded value since I didn't have any other mod instruments installed so I never realized.

Just put up the fix, should fix the issue.

Thanks again, though I'm far from skilled when it comes to Factorio Mods if you ever need an bug-searching eye, help or some feedback I'd be more than happy to return the favor, just get in touch.

**Comment by Minimal-C** [comment]
I'll probably post the official zip on the mod portal a little later on
